# Generated by Django 3.2.9 on 2021-11-07 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='departmentId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50, verbose_name='Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('lastName', models.CharField(max_length=50, verbose_name='Apellido')),
                ('identification', models.CharField(max_length=50, verbose_name='Identificación')),
                ('email', models.EmailField(max_length=50, verbose_name='Correo electronico')),
                ('departmentPerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.departmentid', verbose_name='Departamento por persona')),
            ],
        ),
    ]
